2021-05-08 00:29:04,809 INFO    MainThread:17659 [wandb_setup.py:_flush():69] setting env: {'notebook_name': 'analytics-II-final-workshop'}
2021-05-08 00:29:04,809 INFO    MainThread:17659 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-08 00:29:04,815 INFO    MainThread:17659 [wandb_init.py:_log_setup():336] Logging user logs to /home/sebas/projects/analytics-II-workshop/wandb/run-20210508_002904-bfc2t6aj/logs/debug.log
2021-05-08 00:29:04,815 INFO    MainThread:17659 [wandb_init.py:_log_setup():337] Logging internal logs to /home/sebas/projects/analytics-II-workshop/wandb/run-20210508_002904-bfc2t6aj/logs/debug-internal.log
2021-05-08 00:29:04,817 INFO    MainThread:17659 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7ecc038080>
2021-05-08 00:29:04,828 INFO    MainThread:17659 [wandb_init.py:init():369] calling init triggers
2021-05-08 00:29:04,828 INFO    MainThread:17659 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 1000, 'batch_size': 64, 'losses': {'reg': 'mse', 'class': 'binary_crossentropy'}, 'metrics': {'reg': [<tensorflow.python.eager.def_function.Function object at 0x7ee6df96a0>, <function mean_absolute_percentage_error at 0x7f48c9f048>], 'class': []}, 'window_size': 30, 'architecture': 'Conv1D', 'dataset-link': 'https://archive.ics.uci.edu/ml/datasets/Ozone+Level+Detection', 'dataset': 'Ozone Level Detection'}
2021-05-08 00:29:04,829 INFO    MainThread:17659 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 26obusi4
2021-05-08 00:29:04,835 INFO    MainThread:17659 [wandb_run.py:finish():1208] finishing run sebastian-garcia-acosta/analytics-II-final-workshop/26obusi4
2021-05-08 00:29:04,840 INFO    MainThread:17659 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-08 00:29:04,840 INFO    MainThread:17659 [wandb_run.py:_restore():1507] restore
2021-05-08 00:29:04,857 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 548
  total_bytes: 548
}

2021-05-08 00:29:05,448 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 548
  total_bytes: 548
}

2021-05-08 00:29:06,229 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 548
  total_bytes: 5774
}

2021-05-08 00:29:06,848 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 548
  total_bytes: 5788
}

2021-05-08 00:29:06,956 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 548
  total_bytes: 5788
}

2021-05-08 00:29:07,062 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 548
  total_bytes: 5788
}

2021-05-08 00:29:07,169 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 548
  total_bytes: 5788
}

2021-05-08 00:29:07,275 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 548
  total_bytes: 5788
}

2021-05-08 00:29:07,381 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5788
  total_bytes: 5788
}

2021-05-08 00:29:07,491 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5788
  total_bytes: 5788
}

2021-05-08 00:29:07,597 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5788
  total_bytes: 5788
}

2021-05-08 00:29:07,703 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5788
  total_bytes: 5788
}

2021-05-08 00:29:07,809 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5788
  total_bytes: 5788
}

2021-05-08 00:29:07,916 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5788
  total_bytes: 5788
}

2021-05-08 00:29:08,022 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5788
  total_bytes: 5788
}

2021-05-08 00:29:08,128 INFO    MainThread:17659 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5788
  total_bytes: 5788
}

2021-05-08 00:29:10,459 INFO    MainThread:17659 [wandb_run.py:_show_files():1879] logging synced files
2021-05-08 00:29:10,482 INFO    MainThread:17659 [wandb_init.py:init():418] starting backend
2021-05-08 00:29:10,483 INFO    MainThread:17659 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-08 00:29:10,496 INFO    MainThread:17659 [backend.py:ensure_launched():132] starting backend process...
2021-05-08 00:29:10,550 INFO    MainThread:17659 [backend.py:ensure_launched():137] started backend process with pid: 18275
2021-05-08 00:29:10,553 INFO    MainThread:17659 [wandb_init.py:init():423] backend started and connected
2021-05-08 00:29:10,635 INFO    MainThread:17659 [wandb_init.py:init():465] updated telemetry
2021-05-08 00:29:10,637 INFO    MainThread:17659 [wandb_init.py:init():484] communicating current version
2021-05-08 00:29:14,243 INFO    MainThread:17659 [wandb_init.py:init():489] got version response 
2021-05-08 00:29:14,243 INFO    MainThread:17659 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-08 00:29:14,541 INFO    MainThread:17659 [wandb_init.py:init():522] starting run threads in backend
2021-05-08 00:29:19,562 INFO    MainThread:17659 [wandb_run.py:_console_start():1565] atexit reg
2021-05-08 00:29:19,564 INFO    MainThread:17659 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-08 00:29:19,564 INFO    MainThread:17659 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-08 00:29:19,565 INFO    MainThread:17659 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-08 00:29:19,565 INFO    MainThread:17659 [wandb_init.py:init():546] run started, returning control to user process
2021-05-08 00:29:19,567 INFO    MainThread:17659 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-08 00:29:19,567 INFO    MainThread:17659 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-08 00:29:19,599 INFO    MainThread:17659 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-08 00:29:25,672 INFO    MainThread:17659 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-08 00:29:25,673 INFO    MainThread:17659 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-08 00:29:25,689 INFO    MainThread:17659 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-08 00:29:25,829 INFO    MainThread:17659 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-08 00:29:25,829 INFO    MainThread:17659 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-08 00:29:25,851 INFO    MainThread:17659 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-08 00:29:25,874 INFO    MainThread:17659 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-08 00:29:25,874 INFO    MainThread:17659 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-08 00:29:42,314 INFO    MainThread:17659 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-08 00:29:43,769 INFO    MainThread:17659 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-08 00:29:43,769 INFO    MainThread:17659 [jupyter.py:save_ipynb():265] not saving jupyter notebook
